2025-01-16 23:06:07.871 | INFO     | __main__:setup_driver:86 - ChromeDriverの設定が完了しました
2025-01-16 23:06:07.877 | INFO     | __main__:login:104 - ログイン処理を開始
2025-01-16 23:06:09.056 | INFO     | __main__:login:106 - 現在のURL: https://crowdworks.jp/login
2025-01-16 23:06:11.061 | INFO     | __main__:login:113 - ログインフォームの要素を探索中...
2025-01-16 23:06:11.065 | INFO     | __main__:login:133 - ログインフォームの要素を発見
2025-01-16 23:06:13.085 | INFO     | __main__:login:157 - ログインボタンをクリック
2025-01-16 23:06:18.842 | INFO     | __main__:login:166 - ログイン後のURL: https://crowdworks.jp/dashboard
2025-01-16 23:06:18.849 | INFO     | __main__:login:168 - ログイン成功
2025-01-16 23:06:18.850 | INFO     | __main__:scrape_jobs:206 - 案件情報の取得を開始
2025-01-16 23:06:24.894 | ERROR    | __main__:scrape_jobs:255 - 案件データの取得中にエラーが発生: 'NoneType' object has no attribute 'find'
2025-01-16 23:06:24.895 | ERROR    | __main__:scrape_jobs:255 - 案件データの取得中にエラーが発生: 'NoneType' object has no attribute 'find'
2025-01-16 23:06:24.895 | ERROR    | __main__:scrape_jobs:255 - 案件データの取得中にエラーが発生: 'NoneType' object has no attribute 'find'
2025-01-16 23:06:24.895 | ERROR    | __main__:scrape_jobs:255 - 案件データの取得中にエラーが発生: 'NoneType' object has no attribute 'find'
2025-01-16 23:06:24.896 | ERROR    | __main__:scrape_jobs:255 - 案件データの取得中にエラーが発生: 'NoneType' object has no attribute 'find'
2025-01-16 23:06:24.896 | ERROR    | __main__:scrape_jobs:255 - 案件データの取得中にエラーが発生: 'NoneType' object has no attribute 'find'
2025-01-16 23:06:24.896 | ERROR    | __main__:scrape_jobs:255 - 案件データの取得中にエラーが発生: 'NoneType' object has no attribute 'find'
2025-01-16 23:06:24.896 | ERROR    | __main__:scrape_jobs:255 - 案件データの取得中にエラーが発生: 'NoneType' object has no attribute 'find'
2025-01-16 23:06:24.897 | ERROR    | __main__:scrape_jobs:255 - 案件データの取得中にエラーが発生: 'NoneType' object has no attribute 'find'
2025-01-16 23:06:24.897 | ERROR    | __main__:scrape_jobs:255 - 案件データの取得中にエラーが発生: 'NoneType' object has no attribute 'find'
2025-01-16 23:06:24.897 | ERROR    | __main__:scrape_jobs:255 - 案件データの取得中にエラーが発生: 'NoneType' object has no attribute 'find'
2025-01-16 23:06:24.897 | ERROR    | __main__:scrape_jobs:255 - 案件データの取得中にエラーが発生: 'NoneType' object has no attribute 'find'
2025-01-16 23:06:24.898 | ERROR    | __main__:scrape_jobs:255 - 案件データの取得中にエラーが発生: 'NoneType' object has no attribute 'find'
2025-01-16 23:06:24.898 | ERROR    | __main__:scrape_jobs:255 - 案件データの取得中にエラーが発生: 'NoneType' object has no attribute 'find'
2025-01-16 23:06:24.898 | ERROR    | __main__:scrape_jobs:255 - 案件データの取得中にエラーが発生: 'NoneType' object has no attribute 'find'
2025-01-16 23:06:24.898 | ERROR    | __main__:scrape_jobs:255 - 案件データの取得中にエラーが発生: 'NoneType' object has no attribute 'find'
2025-01-16 23:06:24.899 | ERROR    | __main__:scrape_jobs:255 - 案件データの取得中にエラーが発生: 'NoneType' object has no attribute 'find'
2025-01-16 23:06:24.899 | ERROR    | __main__:scrape_jobs:255 - 案件データの取得中にエラーが発生: 'NoneType' object has no attribute 'find'
2025-01-16 23:06:24.900 | ERROR    | __main__:scrape_jobs:255 - 案件データの取得中にエラーが発生: 'NoneType' object has no attribute 'find'
2025-01-16 23:06:24.900 | ERROR    | __main__:scrape_jobs:255 - 案件データの取得中にエラーが発生: 'NoneType' object has no attribute 'find'
2025-01-16 23:06:24.900 | ERROR    | __main__:scrape_jobs:255 - 案件データの取得中にエラーが発生: 'NoneType' object has no attribute 'find'
2025-01-16 23:06:24.901 | ERROR    | __main__:scrape_jobs:255 - 案件データの取得中にエラーが発生: 'NoneType' object has no attribute 'find'
2025-01-16 23:06:24.901 | ERROR    | __main__:scrape_jobs:255 - 案件データの取得中にエラーが発生: 'NoneType' object has no attribute 'find'
2025-01-16 23:06:24.901 | ERROR    | __main__:scrape_jobs:255 - 案件データの取得中にエラーが発生: 'NoneType' object has no attribute 'find'
2025-01-16 23:06:24.902 | ERROR    | __main__:scrape_jobs:255 - 案件データの取得中にエラーが発生: 'NoneType' object has no attribute 'find'
2025-01-16 23:06:24.903 | ERROR    | __main__:scrape_jobs:255 - 案件データの取得中にエラーが発生: 'NoneType' object has no attribute 'find'
2025-01-16 23:06:24.903 | ERROR    | __main__:scrape_jobs:255 - 案件データの取得中にエラーが発生: 'NoneType' object has no attribute 'find'
2025-01-16 23:06:24.903 | ERROR    | __main__:scrape_jobs:255 - 案件データの取得中にエラーが発生: 'NoneType' object has no attribute 'find'
2025-01-16 23:06:24.904 | ERROR    | __main__:scrape_jobs:255 - 案件データの取得中にエラーが発生: 'NoneType' object has no attribute 'find'
2025-01-16 23:06:24.904 | ERROR    | __main__:scrape_jobs:255 - 案件データの取得中にエラーが発生: 'NoneType' object has no attribute 'find'
2025-01-16 23:06:24.904 | ERROR    | __main__:scrape_jobs:255 - 案件データの取得中にエラーが発生: 'NoneType' object has no attribute 'find'
2025-01-16 23:06:24.905 | ERROR    | __main__:scrape_jobs:255 - 案件データの取得中にエラーが発生: 'NoneType' object has no attribute 'find'
2025-01-16 23:06:24.905 | ERROR    | __main__:scrape_jobs:255 - 案件データの取得中にエラーが発生: 'NoneType' object has no attribute 'find'
2025-01-16 23:06:24.905 | ERROR    | __main__:scrape_jobs:255 - 案件データの取得中にエラーが発生: 'NoneType' object has no attribute 'find'
2025-01-16 23:06:24.906 | ERROR    | __main__:scrape_jobs:255 - 案件データの取得中にエラーが発生: 'NoneType' object has no attribute 'find'
2025-01-16 23:06:24.906 | ERROR    | __main__:scrape_jobs:255 - 案件データの取得中にエラーが発生: 'NoneType' object has no attribute 'find'
2025-01-16 23:06:24.906 | ERROR    | __main__:scrape_jobs:255 - 案件データの取得中にエラーが発生: 'NoneType' object has no attribute 'find'
2025-01-16 23:06:24.906 | ERROR    | __main__:scrape_jobs:255 - 案件データの取得中にエラーが発生: 'NoneType' object has no attribute 'find'
2025-01-16 23:06:24.907 | ERROR    | __main__:scrape_jobs:255 - 案件データの取得中にエラーが発生: 'NoneType' object has no attribute 'find'
2025-01-16 23:06:24.907 | ERROR    | __main__:scrape_jobs:255 - 案件データの取得中にエラーが発生: 'NoneType' object has no attribute 'find'
2025-01-16 23:06:24.907 | ERROR    | __main__:scrape_jobs:255 - 案件データの取得中にエラーが発生: 'NoneType' object has no attribute 'find'
2025-01-16 23:06:24.907 | ERROR    | __main__:scrape_jobs:255 - 案件データの取得中にエラーが発生: 'NoneType' object has no attribute 'find'
2025-01-16 23:06:24.908 | ERROR    | __main__:scrape_jobs:255 - 案件データの取得中にエラーが発生: 'NoneType' object has no attribute 'find'
2025-01-16 23:06:24.908 | ERROR    | __main__:scrape_jobs:255 - 案件データの取得中にエラーが発生: 'NoneType' object has no attribute 'find'
2025-01-16 23:06:24.908 | ERROR    | __main__:scrape_jobs:255 - 案件データの取得中にエラーが発生: 'NoneType' object has no attribute 'find'
2025-01-16 23:06:24.909 | ERROR    | __main__:scrape_jobs:255 - 案件データの取得中にエラーが発生: 'NoneType' object has no attribute 'find'
2025-01-16 23:06:24.909 | ERROR    | __main__:scrape_jobs:255 - 案件データの取得中にエラーが発生: 'NoneType' object has no attribute 'find'
2025-01-16 23:06:24.909 | ERROR    | __main__:scrape_jobs:255 - 案件データの取得中にエラーが発生: 'NoneType' object has no attribute 'find'
2025-01-16 23:06:24.910 | ERROR    | __main__:scrape_jobs:255 - 案件データの取得中にエラーが発生: 'NoneType' object has no attribute 'find'
2025-01-16 23:06:24.910 | ERROR    | __main__:scrape_jobs:255 - 案件データの取得中にエラーが発生: 'NoneType' object has no attribute 'find'
2025-01-16 23:06:24.910 | ERROR    | __main__:scrape_jobs:255 - 案件データの取得中にエラーが発生: 'NoneType' object has no attribute 'find'
2025-01-16 23:06:24.910 | ERROR    | __main__:scrape_jobs:255 - 案件データの取得中にエラーが発生: 'NoneType' object has no attribute 'find'
2025-01-16 23:06:24.911 | ERROR    | __main__:scrape_jobs:255 - 案件データの取得中にエラーが発生: 'NoneType' object has no attribute 'find'
2025-01-16 23:06:24.911 | ERROR    | __main__:scrape_jobs:255 - 案件データの取得中にエラーが発生: 'NoneType' object has no attribute 'find'
2025-01-16 23:06:24.911 | ERROR    | __main__:scrape_jobs:255 - 案件データの取得中にエラーが発生: 'NoneType' object has no attribute 'find'
2025-01-16 23:06:24.912 | ERROR    | __main__:scrape_jobs:255 - 案件データの取得中にエラーが発生: 'NoneType' object has no attribute 'find'
2025-01-16 23:06:24.912 | ERROR    | __main__:scrape_jobs:255 - 案件データの取得中にエラーが発生: 'NoneType' object has no attribute 'find'
2025-01-16 23:06:24.912 | INFO     | __main__:scrape_jobs:258 - 0件の案件を取得
2025-01-16 23:06:24.913 | WARNING  | __main__:save_jobs:269 - 保存する案件データがありません
2025-01-16 23:06:25.006 | INFO     | __main__:run:301 - クローラーを終了します
